name: oggmap_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - alive-progress>=3.2.0
  - anndata>=0.11.3
  - biopython>=1.85
  - numba>=0.61.0
  - numpy<2.2,>=1.24
  - pandas>=2.2.3
  - pip
  - pytest
  - python=3.10
  - python-wget>=3.2
  - scipy>=1.15.1
  - seaborn>=0.13.2
  - setuptools>=67.6.0
  - statannot>=0.2.3
  - pip:
      - harmonypy>=0.0.10
      - leidenalg>=0.10.2
      - scanpy>=1.11.0
      - taxadb2>=0.12.3
      - umap-learn>=0.5.7
