name: oggmap_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - setuptools>=67.6.0
  - numpy<2.2,>=1.24
  - numba>=0.61.0
  - scipy>=1.15.1
  - pandas>=2.2.3
  - anndata>=0.11.3
  - scanpy>=1.11.0
  - seaborn>=0.13.2
  - statannot>=0.2.3
  - alive-progress>=3.2.0
  - biopython>=1.85
  - taxadb2>=0.12.3
  - python-wget>=3.2
  - pytest
  - pip
  - pip:
      - harmonypy>=0.0.10
      - leidenalg>=0.10.2
      - umap-learn>=0.5.7
      - nbsphinx
      - myst-nb
      - ipykernel
      - sphinx-rtd-theme